export const products = [
  {
    id: 1,
    name: 'Product 1',
    price: 10,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 2,
    name: 'Product 2',
    price: 20,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 3,
    name: 'Product 3',
    price: 30,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 4,
    name: 'Product 4',
    price: 40,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 5,
    name: 'Product 5',
    price: 50,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 6,
    name: 'Product 6',
    price: 60,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 7,
    name: 'Product 7',
    price: 70,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 8,
    name: 'Product 8',
    price: 80,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 9,
    name: 'Product 9',
    price: 90,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 10,
    name: 'Product 10',
    price: 100,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 11,
    name: 'Product 11',
    price: 110,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
  {
    id: 12,
    name: 'Product 12',
    price: 120,
    image: 'https://via.placeholder.com/150',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.',
  },
];